#!/bin/bash

psql < sql/structure.sql
psql -d forum < sql/utility.sql
psql -d forum < sql/trigger-funcs.sql
psql -d forum < sql/triggers.sql
psql -d forum < sql/create-update.sql
psql -d forum < sql/data.sql
