#!/bin/bash

psql < sql/structure.sql
psql -d yeti-threads < sql/utility.sql
psql -d yeti-threads < sql/trigger-funcs.sql
psql -d yeti-threads < sql/triggers.sql
psql -d yeti-threads < sql/create-update.sql
psql -d yeti-threads < sql/data.sql
